apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: autodoc-api
    newTag: COMMIT_SHA_PLACEHOLDER
  - name: autodoc-worker
    newTag: COMMIT_SHA_PLACEHOLDER
  - name: autodoc-flow
    newTag: COMMIT_SHA_PLACEHOLDER
  - name: prefecthq/prefect
    newTag: 3-latest

patches:
  - path: patches/replicas.yaml
  - path: patches/config.yaml
  - path: patches/secrets.yaml
  - path: patches/resource-quota.yaml
