apiVersion: v1
kind: Secret
metadata:
  name: autodoc-api-keys
  namespace: autodoc
  labels:
    app.kubernetes.io/part-of: autodoc
type: Opaque
stringData:
  GOOGLE_API_KEY: "CHANGE_ME"
  OPENAI_API_KEY: "CHANGE_ME"
  GITHUB_DEFAULT_TOKEN: "CHANGE_ME"
