apiVersion: v1
kind: Secret
metadata:
  name: autodoc-redis-credentials
  namespace: autodoc
  labels:
    app.kubernetes.io/part-of: autodoc
type: Opaque
stringData:
  PREFECT_REDIS_MESSAGING_HOST: "redis-host"
  PREFECT_REDIS_MESSAGING_PORT: "6379"
