from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass
from pathlib import Path

from prefect import task

from src.database.models.repository import Repository
from src.errors import TransientError
from src.providers.base import get_provider
from src.services.config_loader import AutodocConfig

logger = logging.getLogger(__name__)


@dataclass
class ScopeReadme:
    """A README produced for a single documentation scope."""

    content: str
    config: AutodocConfig


@task(name="close_stale_autodoc_prs")
async def close_stale_autodoc_prs(
    *,
    repository: Repository,
    branch: str,
) -> int:
    """Close open autodoc PRs matching branch pattern ``autodoc/{repo_name}-{branch}-*``.

    Returns count of closed PRs.
    """
    provider = get_provider(repository.provider)
    branch_pattern = f"autodoc/{repository.name}-{branch}-"

    count = await provider.close_stale_prs(
        url=repository.url,
        branch_pattern=branch_pattern,
        access_token=repository.access_token,
    )
    logger.info("Closed %d stale autodoc PRs for %s/%s", count, repository.name, branch)
    return count


@task(name="create_autodoc_pr", retries=1, retry_delay_seconds=5)
async def create_autodoc_pr(
    *,
    repository: Repository,
    branch: str,
    job_id: uuid.UUID,
    scope_readmes: list[ScopeReadme],
    repo_path: str,
) -> str:
    """Create autodoc PR with README content from one or more scopes.

    1. Create branch: ``autodoc/{repo_name}-{branch}-{job_id_short}-{YYYY-MM-DD}``
    2. Write all README files to disk (each at its scope-relative output_path)
    3. Commit and push
    4. Create PR targeting default branch (``public_branch``)

    PR settings (auto_merge, reviewers) are taken from the first scope's config.

    Args:
        repository: Repository ORM object.
        branch: Target branch name.
        job_id: Job UUID.
        scope_readmes: List of ScopeReadme entries (one per scope that produced a README).
        repo_path: Path to cloned repository on disk.

    Returns:
        PR URL.
    """
    import asyncio
    from datetime import UTC, datetime
    from urllib.parse import urlparse

    provider = get_provider(repository.provider)
    today = datetime.now(tz=UTC).strftime("%Y-%m-%d")
    job_short = str(job_id)[:8]
    pr_branch = f"autodoc/{repository.name}-{branch}-{job_short}-{today}"

    # Write all README files relative to their scope_path.
    # For root scope (scope_path="."), this is just output_path.
    # For nested scopes (e.g. "packages/auth"), the README lands inside that dir.
    added_paths: list[str] = []
    for scope_readme in scope_readmes:
        relative_readme = str(
            Path(scope_readme.config.scope_path) / scope_readme.config.readme.output_path
        )
        readme_path = Path(repo_path) / relative_readme
        readme_path.parent.mkdir(parents=True, exist_ok=True)
        readme_path.write_text(scope_readme.content, encoding="utf-8")
        added_paths.append(relative_readme)

    # Git operations
    async def _git(*args: str) -> str:
        proc = await asyncio.create_subprocess_exec(
            "git",
            *args,
            cwd=repo_path,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if proc.returncode != 0:
            raise TransientError(f"git {args[0]} failed: {stderr.decode()}")
        return stdout.decode().strip()

    await _git("checkout", "-b", pr_branch)
    for path in added_paths:
        await _git("add", path)
    await _git("commit", "-m", f"docs: update documentation for {branch}")

    # Push — inject token for auth
    push_url = repository.url
    if repository.access_token:
        parsed = urlparse(repository.url)
        if repository.provider == "github":
            push_url = (
                f"https://{repository.access_token}@{parsed.hostname}{parsed.path}"
            )
        else:  # bitbucket
            push_url = (
                f"https://x-token-auth:{repository.access_token}"
                f"@{parsed.hostname}{parsed.path}"
            )

    await _git("push", push_url, pr_branch)

    # For PR config, use the first scope's settings
    pr_config = scope_readmes[0].config
    scope_count = len(scope_readmes)
    scope_list = ", ".join(sr.config.scope_path for sr in scope_readmes)

    pr_url = await provider.create_pull_request(
        url=repository.url,
        branch=pr_branch,
        target_branch=repository.public_branch,
        title=f"docs: update documentation for {branch}",
        body=(
            f"Automated documentation update generated by AutoDoc.\n\n"
            f"Job ID: {job_id}\n"
            f"Branch: {branch}\n"
            f"Scopes: {scope_count} ({scope_list})"
        ),
        access_token=repository.access_token,
        reviewers=pr_config.pull_request.reviewers or None,
        auto_merge=pr_config.pull_request.auto_merge,
    )

    logger.info("Created PR: %s (scopes: %s)", pr_url, scope_list)
    return pr_url
